import { PatientData } from './types';

const patients: PatientData = [
    {
        height: 170,
        weight: 60,
        male: true,
        age: 52,
        neckCircumference: 45,
        highBloodPressure: false,
        snore: false,
        dailyFatigue: false,
        sleepChoking: false,
        sleepApnoea: false,
    },
    {
        height: 200,
        weight: 100,
        male: true,
        age: 52,
        neckCircumference: 45,
        highBloodPressure: false,
        snore: false,
        dailyFatigue: false,
        sleepChoking: false,
        sleepApnoea: false,
    },
    {
        height: 180,
        weight: 300,
        male: false,
        age: 52,
        neckCircumference: 45,
        highBloodPressure: false,
        snore: false,
        dailyFatigue: false,
        sleepChoking: false,
        sleepApnoea: false,
    },
    {
        height: 170,
        weight: 60,
        male: false,
        age: 52,
        neckCircumference: 45,
        highBloodPressure: true,
        snore: false,
        dailyFatigue: false,
        sleepChoking: false,
        sleepApnoea: false,
    },
    {
        height: 180,
        weight: 100,
        male: true,
        age: 22,
        neckCircumference: 25,
        highBloodPressure: false,
        snore: true,
        dailyFatigue: true,
        sleepChoking: false,
        sleepApnoea: false,
    },
];
